### ISSUE TITLE
Dangling WolframKernel instances

### ISSUE THREAD

**Issue by oblitum** [kenkangxgwe/lsp-wl#10]
Using it with [coc-lsp-wl](https://github.com/voldikss/coc-lsp-wl), when I close Vim, the WolframKernel instance started by the editor is left dangling when the editor is closed. Does the plugin have to do something in particular to close it? The WolframKernel instances keep accumulating and the fix I know of is to `killall -9`.

**Comment by kenkangxgwe** [comment]
Every client has to explicitly send a `Shutdown` request to the language server. I just checked the log file, it did not send any `Shutdown` request or even `Exit` notification. 

However, on Windows, the language server is a child thread that will automatically terminate if its parent (nvim/vim) exits. I have no idea why it does not do the same thing on Linux.

Do you know if there is an existing command to close the workspace and shut down the server w/o closing the editor? That will help me debug the problem.

**Comment by oblitum** [comment]
Hi, sorry but I don't have much knowledge on LSP implementation. I think it's good idea to report this one to coc-lsp-wl, don't you think?

**Comment by oblitum** [comment]
If you think there's anything to fix on this side feel free to reopen.

I'm not sure whether exiting relates to cancellation but I've learned of the following recently, which possibly may have some relation to this:

https://github.com/fannheyward/coc-texlab/issues/2#issuecomment-517725019
https://github.com/latex-lsp/texlab/issues/47
