### ISSUE TITLE
A small article about installing this project.

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#12]
I installed it several days ago, met several problems. Finally I overcome them, and hope this article can help others.Besides, it is awesome!

<https://zhuanlan.zhihu.com/p/88607694>

**Comment by kenkangxgwe** [comment]
Thanks @wuyudi . Hope you enjoy this plugin.

Let's add this to wiki so that I can close the issue. Seems that the main reason of failure is the dependency issue. I will elaborate on that in the wiki.
