### ISSUE TITLE
Completion of $Abcdefg gives $$Abcdefg.

### ISSUE THREAD

**Issue by asdasd1dsadsa** [kenkangxgwe/lsp-wl#13]

**Comment by kenkangxgwe** [comment]
Thanks for your feedback. I've noticed this bug once but forgot about it later. I will push a commit soon.

**Comment by kenkangxgwe** [comment]
@asdasd1dsadsa please confirm the latest commit works for you, thanks.

**Comment by asdasd1dsadsa** [comment]
OK
