### ISSUE TITLE
Running test failed

### ISSUE THREAD

**Issue by paulps2** [kenkangxgwe/lsp-wl#15]
I'm new to VS Code and this extension. I tried to install it and run the test with `wolframscript /path/to/lsp-wl/init.wls --test, -t`. It returns the following error:

```
Running tests for all.

FileExistsQ::badfile: The specified argument AST`Library`Private`CompiledLibrary[/Users/User/Library/Mathematica/Paclets/Repository/AST-0.15/LibraryResources/MacOSX-x86-64/expr.dylib] should be a valid string or File.
Column[{Column[{TableForm[{{Test: , WolframLanguageServer`Test`TextDocumentTest`}, {Test passed: , {{3, /, 3}}}, {Time Elapsed: , Quantity[0.0008230000000000001`2.588793578324601, Seconds]}}], Column[{}]}]}]
```

The extension also does not seem to be started in my VS Code. I have already install the AST and Lint Paclet with `{PacletInstall["AST", "UpdateSites" -> True], PacletInstall["Lint", "UpdateSites" -> True]}` in Mathematica and it returns `{Paclet[AST, 0.15, <>], Paclet[Lint, 0.15, <>]}`, which means that the 2 paclets seem to be rightly installed.

Am I doing something wrong here?

**Comment by kenkangxgwe** [comment]
Hi @paulps2 , AST and Lint 0.15 were just released last week. I will add the support for 0.15 in `develop branch` soon. Please stay informed. Thanks for your feedback.

**Comment by kenkangxgwe** [comment]
Hi @paulps2 , please try the latest `master`/`develop` branch. The error is still there but not affecting normal usage.
