### ISSUE TITLE
the develop branch seems could be merged to master branch?

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#16]
as the title said.

**Comment by kenkangxgwe** [comment]
You are correct, many changes happened in the dev branch. Let me try releasing a Lunar Year Update for this decade.

**Comment by kenkangxgwe** [comment]
Closed by 34bfee18c83460153a9ea4a1fa9378a9cac087fb. Feel free to test it. I will also update the README for vscode plugin shortly.
