### ISSUE TITLE
FileExistsQ::badfile: expr.dylib

### ISSUE THREAD

**Issue by ddyok** [kenkangxgwe/lsp-wl#17]
Upon running init.wls I get:

```
[INFO  2020-01-25T11:16:51] Initializing Wolfram Language Server

FileExistsQ::badfile: 
   The specified argument AST`Library`Private`CompiledLibrary[/Users/ddyok/Lib
      rary/WolframEngine/Paclets/Repository/AST-0.15/LibraryResources/MacOSX-x
      86-64/expr.dylib] should be a valid string or File.
[INFO  2020-01-25T11:16:53] Language server is connecting the client through
socket.

SocketConnect::zmqexception: 
   A ZeroMQLink exception was thrown - Connection refused (code 61)
[ERROR 2020-01-25T11:16:53] Cannot connect to client via socket.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Is this on my end?

**Comment by kenkangxgwe** [comment]
Hi, this is a known issue from the AST packet. I have contacted the writer and he will push a patch soon. But this should not be a problem. The server is still working normally on my side.

**Comment by ddyok** [comment]
> The server is still working normally on my side.

The process does stop, it seems:

```
[INFO  2020-01-25T11:16:53] Language server is connecting the client through
socket.

SocketConnect::zmqexception: 
   A ZeroMQLink exception was thrown - Connection refused (code 61)
[ERROR 2020-01-25T11:16:53] Cannot connect to client via socket.
```

But in any case, I'll wait for the patch and try again.

(By the way, forgot to add: Great project. Really helpful and much better when composing bigger code projects than inline mathematica notebooks - good Job!).

**Comment by kenkangxgwe** [comment]
Thank you. Usually the connection refusal is caused by port conflict. Try
assigning another port in the extension settings.

**Comment by kenkangxgwe** [comment]
Hi, does it work for you now?

**Comment by ddyok** [comment]
Yes, it was a used port, like you said. This is an AST issue.

**Comment by weihongliang233** [comment]
I encountered a similar problem when running init.wls.  According to your discussion, it is probably because the conflict of the port. So I try to assign a port which is not occupied. It can be tested with the command "lsof -i". However, even if the "lsof -i" showed that this port is free, it still come out with the "Connection refused" error. I have tried several ports, but it didn't work.
```
ubuntu@VM-0-17-ubuntu:~/My_Dailywork/Git_Version_Control/lsp-wl$ sudo lsof -i:9000
ubuntu@VM-0-17-ubuntu:~/My_Dailywork/Git_Version_Control/lsp-wl$ wolframscript -f /home/ubuntu/My_Dailywork/Git_Version_Control/lsp-wl/init.wls --socket=9000
[INFO  2020-06-30T17:41:45] Initializing Wolfram Language Server
[INFO  2020-06-30T17:41:48] Language server is connecting the client through
socket.

SocketConnect::zmqexception: 
   A ZeroMQLink exception was thrown - Connection refused (code 111)
[ERROR 2020-06-30T17:41:48] Cannot connect to client via socket.
```

**Comment by kenkangxgwe** [comment]
Could you try `SocketOpen[9000]` in MMA to see whether it works for you?
