### ISSUE TITLE
an advice( Inspired by the C++ language plugin)

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#18]
for example:
When I type `Plot` ,it will show this.
![image](https://user-images.githubusercontent.com/30024051/73561244-92409580-4450-11ea-8197-193169a63a81.png)
after that,I want to type, for example : `Plot[x,{x,0,5}]`
but after I type `[]` , I have to type the format by memory.
Can it show the hint like this? (though C++ is huge different from mma)
![image](https://user-images.githubusercontent.com/30024051/73561559-1bf06300-4451-11ea-8ef6-d575da992949.png)
After I type something and a comma , it will change the highlight.
![image](https://user-images.githubusercontent.com/30024051/73561694-5e19a480-4451-11ea-8f59-18173fa7d0f4.png)

**Comment by kenkangxgwe** [comment]
Hi, what you said is an LSP feature called `textDocument/signatureHelp`, I tried to implement it in `feature/signatrueHelp` branch, but there are some pending issues.

* The performance is not very good since VSCode sends the request every time the cursor moves.
* It is hard to design how to hide the `signatureHelp` floating window.  
Let's say we have a piece of code like:
  ```mathematica
  f[a, g[b, h[c, d, e|], 
  ```
  The `|` stands for the current cursor position and the `signatureHelp` of function `h` is showing. When the user moves the cursor out of function `h`, say
  ```mathematica
  f[a, g[b, h[c, d, e],| 
  ```
  it seems that `signatureHelp` should not disappear, instead, it should show the info of function `g`. Given the fact that Wolfram Language is merely a bunch of nested functions, especially when you are in a large `Module` or `Block` function, if users want to hide the annoying signatureHelp, what should they do? I hope there would be a LSP request like `hideSignatureHelp`, so this can be handled elegantly.

Let me consider this again more deeply. Meanwhile, please give any feedback if you have ideas.

**Comment by wuyudi** [comment]
i have an immature idea.

Since we write mma code in a "stack-like" way. for example: `Plot[Log[2,x] ,{x,0,5}]`

1. first type `Plot[]` , then `Plot` is push in the "stack". 
| `Plot` |
2. type `Log[]` . `Log` push in the top of stack. like this.
| `Log` |
| `Plot` |
3. finished typing `Log[2,x]` ,move the cursor out of `Log` , `Log` pop out.
|`Plot`|
4. finish. `Plot` pop out. Stack empty.

and maybe the `signatureHelp` could appear as the same way?

1. show 
![image](https://user-images.githubusercontent.com/30024051/73664693-bd68f600-4697-11ea-9281-15fba6e6aae6.png)
2. show
![image](https://user-images.githubusercontent.com/30024051/73664753-d96c9780-4697-11ea-9b37-0c306fa92592.png)

3. show as 1

4. show nothing.

And since the stack may be very deep . for example `f[parm, g[parm, h[ parm ], parm]  ,parm]` so maybe there can be a parameter to decide how many signatureHelp could be shown at a time. 
and there maybe can put a slide to handle extra things? And the final effect I thought is this.
![image](https://user-images.githubusercontent.com/30024051/73665504-1edd9480-4699-11ea-9db6-dad935965f19.png)

Just an imagination. Hoping could help.

**Comment by kenkangxgwe** [comment]
Your suggestion sounds a good approach, but given users always input the params for the top function in the stack, it will take much fewer resources to only render the very function they are currently working on.

The thing I was concerned about in my last reply was how users can hide the `signatureHelp` window. You definitely do not want the window to be always shown when you are reading the code. Especially when you are reading a long `Block` and find the cursor is nowhere to be placed.

![image](https://user-images.githubusercontent.com/8650023/73730855-604b5f80-46ec-11ea-8a17-6ff47c3904d0.png)

**Comment by kenkangxgwe** [comment]
Ok, I confirm that if you are not using Vim emulator, you can use <kbd>Esc</kbd> to hide the window. I think there will be commits pull from the `feature/signatureHelp` branch soon.

**Comment by kenkangxgwe** [comment]
In spite of potential UX problems, this is fixed by f828558867c26f2b788f1517d88e3068ee7d66f3 on `develop` branch. Screenshot:

![image](https://user-images.githubusercontent.com/8650023/73933276-f1f3d200-4890-11ea-8c4d-3996b5b3874f.png)

**Comment by kenkangxgwe** [comment]
Currently, parameters are not highlighted. Multiple signatures are not filtered according to the number of parameters input, because the function signatures are too flexible to predict. E.g. `f[Sequence[a,b],c]` or `a//Map[f]`

**Comment by wuyudi** [comment]
Today I come up with this: `SSSTriangle[## & @@ {a, b, c}]`

In notebook,
![image](https://user-images.githubusercontent.com/30024051/74089597-b298d180-4a9a-11ea-9564-771942bdf56b.png)

So it seems nearly hasn't solution.

**Comment by kenkangxgwe** [comment]
I am sorry that I don't get you. `SSSTriangle[## & @@ {a, b, c}]` triggers the `signatureHelp` for me.

![image](https://user-images.githubusercontent.com/8650023/74098336-e6d8b600-4acb-11ea-98ae-3f2e13172fcc.png)

Did you mean the red wedge `^` before the `]`? That's what comes from the `SyntaxInformation`:
``` mathematica
In[7]:= SyntaxInformation[SSSTriangle]
Out[7]= {"ArgumentsPattern" -> {_, _, _}}
```
I did have the plan to support it a long time ago, but not it seems better for the `Lint` paclet to support it instead.
