### ISSUE TITLE
how to close/ignore the warning?

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#20]
my `AST` is version `0.15.1` , which is higher than requirement.

![image](https://user-images.githubusercontent.com/30024051/73820204-2d3ac600-47e9-11ea-8579-be9a088b0b15.png)

---

I find it in the `Server.wl` , line 1624

Just change it as follow.

```mathematica
dependencies = {
			{"AST", "0.15.1"},
			{"Lint", "0.15.1"}
		}
```

I didn't come up with a better method for the time being.

**Comment by kenkangxgwe** [comment]
There may be some way for VSCode to suppress the warning from an extension I guess, but I haven't dug into it. I just fixed this with 6a12b81cedaca010b626427f9be69d3228b206d7 on `develop` branch. Please checkout.
