### ISSUE TITLE
Completion provider, triggerCharacters is not String[] but String

### ISSUE THREAD

**Issue by dalanicolai** [kenkangxgwe/lsp-wl#25]
Hi, I am trying to implement a lsp-wl client in emacs (lsp-mode). However, the editor gives an error on completion because the lsp client expects the triggerCharacter to be a String[] instead of String.

I am not a developer, just trying to implement the lsp-client which the lsp-mode author made quite easy to do. However I contacted him about this 'bug' and he mentioned this in his reply (see image below)

![image](https://user-images.githubusercontent.com/18429791/77233063-4e8f2000-6ba5-11ea-96c8-179e63c94214.png)

**Comment by kenkangxgwe** [comment]
Hi Daniel, Thanks for noticing the bug here. I will accept your PR.
Btw, have you tested whether the [setup for emacs in the Wiki](https://github.com/kenkangxgwe/lsp-wl/wiki#gnu-emacs) works for you? Or does your LSP client have more customized features?

**Comment by dalanicolai** [comment]
Hi! Yeah very small fix of course. I did not notice the emacs configuration on the wiki. But indeed this is what I added too. Anyway, I guess without this fix that example did also not work correctly. Now it almost does (only the markdown link in the pop ups is not handeld correctly yet, but I guess that will be fixed soon). Thanks for the nice package, it looks and works great!

**Comment by kenkangxgwe** [comment]
You're welcome. If you have any suggestions on configuration please do not hesitate to contribute to the Wiki.
