### ISSUE TITLE
About Plot in .wls

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#27]
Recently I find this <https://tieba.baidu.com/p/6566049919> 8th floor.
And I try it in wls.

    <<JavaGraphics`
    Plot[x,{x,0,5}]

The picture flash by. So I wonder there maybe some ways to hold it?

PS, if I run it line by line, this is the effect.

![image](https://user-images.githubusercontent.com/30024051/77719661-bac2b700-6fdd-11ea-840d-5c822846b977.png)

PPS, recently I use matlab, and matlab can plot.

this is its code in Code Runner.

    "matlab": "cd $dir && matlab -nosplash -nodesktop -r $fileNameWithoutExt"

I tried to use it on mma's setting.

    "wolframscript -file"

But failed.

**Comment by kenkangxgwe** [comment]
If you run it as a script it will certainly exit after the script finishes. Add an `Input[]` at the end to prevent it from exiting. I will close this since it seems not related to the language server.

**Comment by kenkangxgwe** [comment]
Feel free to reopen it if you think it relates to any potential feature for the lsp.
