### ISSUE TITLE
Doesn't recognize ##

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#29]
Slot can be recognized,but `##` can't.

![image](https://user-images.githubusercontent.com/30024051/81767517-1d0d4380-94c8-11ea-96a5-e3fafcd7a522.png)

> My mouse is on the `##` , but nothing appear.

![GIF](https://user-images.githubusercontent.com/30024051/81767953-382c8300-94c9-11ea-9776-2b627d7fa805.gif)

**Comment by kenkangxgwe** [comment]
I consider you using 11.3? Running `Sequence::usage` in MMA 11.3 returns nothing.
The bug is so dumb. Please try MMA / Wolfram Engine 12.0+.
![image](https://user-images.githubusercontent.com/8650023/81771654-71003400-9498-11ea-8bfb-78a024a3918c.png)

**Comment by wuyudi** [comment]
Thx, this bug is so out of expection XD. FYI, it's `SlotSequence::usage` instead of `Sequence::usage`.
