### ISSUE TITLE
Does't have highlight and have no idea about how to run

### ISSUE THREAD

**Issue by fecet** [kenkangxgwe/lsp-wl#30]
This is my current state.
![image](https://user-images.githubusercontent.com/41792945/87825592-fbef1780-c8a9-11ea-9295-46f8546e6d4c.png)

**Comment by kenkangxgwe** [comment]
See #6, thanks

**Comment by kenkangxgwe** [comment]
Are you able to get the documentation when the cursor hovers on function names? Or symbols in the outlines? If yes then things work properly. May I close this?
