### ISSUE TITLE
FoldWhile in Server.wl should be renamed to fix name clash with new System` symbol introduced in Mathematica 12.2

### ISSUE THREAD

**Issue by BhuvaneshBhatt** [kenkangxgwe/lsp-wl#34]
Basically, FoldWhile is a new System-context symbol in Mathematica version 12.2 and higher:
<img width="765" alt="Screen Shot 2021-01-14 at 11 34 15 AM" src="https://user-images.githubusercontent.com/40013855/104627294-78499400-565c-11eb-8657-6e6d2060c77a.png">

So there is a name clash with the function defined in Server.wl. As far as I can tell, the LSP function and the System-context context function do the same thing, but the LSP function should be renamed to fix the issue.
```
[INFO  2021-01-14T11:09:14] Initializing Wolfram Language Server

SetDelayed::write:
   Tag FoldWhile in FoldWhile[f_, x_, list_List, test_] is Protected.

SetDelayed::write:
   Tag FoldWhile in FoldWhile[f_, list_List, test_] is Protected.
```

**Comment by kenkangxgwe** [comment]
Fixed in b3b85a5 develop branch. It will be merged on master soon. Thanks for the feedback!
