### ISSUE TITLE
High CPU usage on start

### ISSUE THREAD

**Issue by kc9jud** [kenkangxgwe/lsp-wl#4]
Hello, I've just started using lsp-wl, and I've discovered that the WolframKernel process is using 100% of one core as soon as VSCode is launched, and pegs it there. I'm running Mathematica 11.3, and the latest pull of lsp-wl.

**Comment by kenkangxgwe** [comment]
Hi, could you please send the `wlserver.log` under the repo folder? and what system are you using?

**Comment by kenkangxgwe** [comment]
Closed due to no response for a long time. Hope you have resolved it in a newer version.

**Comment by kenkangxgwe** [comment]
Ok, since @megatron0000 has the same issue as yours, I decided to reopen this issue. Although it works fine on Windows, I did reproduce the issue on Linux. Let me confirm whether it happens on MacOSX also. So if you, @kc9jud , see this message, please reply to me with your operating system, thanks.

**Comment by kenkangxgwe** [comment]
Ok, I've confirmed that it works fine on MacOSX. I will start a hot-fix based on #7.

**Comment by kenkangxgwe** [comment]
Hi @kc9jud and @megatron0000 , I believe that this has been solved in f93fb88ffe82f9de1e3068abec70f77cad508e19, please upgrade to the latest version, install the dependencies and check whether you still meet the problem.
