### ISSUE TITLE
[UnexpectedCharacter] Unexpected character: "\:0438".

### ISSUE THREAD

**Issue by p-pavel** [kenkangxgwe/lsp-wl#40]
Good day!

I'v got lots of messages like this (the character is a Cyrillic unicode character as encoded by MMA in notebooks AND .wl files created using frontend).

P.S.:
I'm willing to participate in development of the project. Frankly I tried it several times with VSCode but it never even started wolfram kernel. This issue should be broken in parts probably so please consider is as an initial contact.

Currently the server starts but the only thing that works is getting document outline from the server (no syntax highlighting, no hover info etc). This behaviour persists in both master (that seems to be "more broken") and development branches.

I get both 12.2 and 12.3 prerelease versions installed under macOS and I also use Linux so I can try different combinations.

**Comment by kenkangxgwe** [comment]
Hi Pavel, glad to hear that you give this project several tries. For syntax highlighting, please see #6. Cyrillic letters are expected to be shown as a warning, see https://github.com/WolframResearch/codeinspector/issues/8. It is up to you whether to respect them, and it won't break any other features.

To analysis more about the server, could you please
1. try uncommenting this line in the repo  
https://github.com/kenkangxgwe/lsp-wl/blob/4d2d5a702568a0b5c2327b1e726d6e05fe95f59d/init.wls#L194
2. restart VSCode and open a wolfram project, typing, hovering, or finding definitions 
3. upload the `wlserver.log` under the git repo folder and paste it here, or some online pastebin like https://paste.ubuntu.com/

**Comment by p-pavel** [comment]
> Hi Pavel, glad to hear that you give this project several tries. For syntax highlighting, please see #6. Cyrillic letters are expected to be shown as a warning, see [WolframResearch/codeinspector#8]

Wow, thanks!

(https://github.com/WolframResearch/codeinspector/issues/8). It is up to you whether to respect them, and it won't break any other features.
> 
> To analysis more about the server, could you please
> 
> 1. try uncommenting this line in the repo
>    https://github.com/kenkangxgwe/lsp-wl/blob/4d2d5a702568a0b5c2327b1e726d6e05fe95f59d/init.wls#L194
> 2. restart VSCode and open a wolfram project, typing, hovering, or finding definitions
> 3. upload the `wlserver.log` under the git repo folder and paste it here, or some online pastebin like https://paste.ubuntu.com/

Yep! thank you

**Comment by p-pavel** [comment]
> Hi Pavel, glad to hear that you give this project several tries. For syntax highlighting, please see #6. Cyrillic letters are expected to be shown as a warning, see [WolframResearch/codeinspector#8](https://github.com/WolframResearch/codeinspector/issues/8). It is up to you whether to respect them, and it won't break any other features.

It's all seem understandable except the fact that we're talking about comments here (not even string literals). So If I have 2000 character explanation in comments I get 2000 problems in code. I think it's not an expected behaviour

<img width="558" alt="image" src="https://user-images.githubusercontent.com/415710/112981356-bc303d80-9163-11eb-91aa-c4c192f27d35.png">

**Comment by kenkangxgwe** [comment]
I see the problem. I will add an option to ignore this warning in comments and string literals

**Comment by p-pavel** [comment]
> I see the problem. I will add an option to ignore this warning in comments and string literals

sounds great.

**Comment by kenkangxgwe** [comment]
Now you can add "UnexpectedCharacter" in the `settings.json` file of VSCode to suppress it. See: https://github.com/kenkangxgwe/lsp-wl#diagnostics
