### ISSUE TITLE
ParentDirectory related messages

### ISSUE THREAD

**Issue by p-pavel** [kenkangxgwe/lsp-wl#44]
There're lots of messages in the form:
```mathematica
ParentDirectory::dirnex: 
   Directory Users/ppavel/Projects/wolfram-engine-app-server/paclet/Kernel/App
     Server does not exist.

ParentDirectory::nums: 
   Argument ParentDirectory[Users/ppavel/Projects/wolfram-engine-app-server/pa
      clet/Kernel/AppServer] should be a positive machine-size integer, a
     nonempty string, or a File specification.

ParentDirectory::nums: 
   Argument ParentDirectory[ParentDirectory[Users/ppavel/Projects/wolfram-engi
       ne-app-server/paclet/Kernel/AppServer]] should be a positive
     machine-size integer, a nonempty string, or a File specification.

ParentDirectory::nums: 
   Argument ParentDirectory[ParentDirectory[ParentDirectory[Users/ppavel/Proje
        cts/wolfram-engine-app-server/paclet/Kernel/AppServer]]] should be a
     positive machine-size integer, a nonempty string, or a File
     specification.

General::stop: Further output of ParentDirectory::nums
     will be suppressed during this calculation.

```

**Comment by p-pavel** [comment]
It seems like absolute path is treated as relative. I don't know how to find the reason for this behaviour

**Comment by kenkangxgwe** [comment]
Interesting, I've never try it on MacOS, so the directory lookup here might be a little buggy. 

Could you share the path of the project that you opened (if not a privacy issue)? Since the log is complaining that `Users/ppavel/Projects/wolfram-engine-app-server/paclet/Kernel/AppServer` doesn't exist, I guess, when converting from the URI that VSCode recognizes to the real pathname, there was something wrong.

**Comment by p-pavel** [comment]
> Could you share the path of the project that you opened (if not a privacy issue)? Since the log is complaining that `Users/ppavel/Projects/wolfram-engine-app-server/paclet/Kernel/AppServer` doesn't exist, I guess, when converting from the URI that VSCode recognizes to the real pathname, there was something wrong.

This is really the full path to the project. /Users is macOS analog to /home directory in other flavours of unix-like OSs.

So the path to the folder is indeed /Users/ppavel/Projects/wolfram-engine-app-server/paclet/Kernel/AppServer and the file in this folder is open in VSCode

**Comment by kenkangxgwe** [comment]
I see, could you try the latest commit on `develop` branch (https://github.com/kenkangxgwe/lsp-wl/commit/f01f55ba6a136b46a9c313499c23909047b31edc) to see if the issue is resolved?

**Comment by p-pavel** [comment]
> I see, could you try the latest commit on `develop` branch ([f01f55b](https://github.com/kenkangxgwe/lsp-wl/commit/f01f55ba6a136b46a9c313499c23909047b31edc)) to see if the issue is resolved?

I tried the latest commit (27f274b87128ab3cc902e0199c4fbd1ae53d9d1e) and indeed it seems like fixed the issue.

You're cool! :)
