### ISSUE TITLE
插件的报错数量有上限

### ISSUE THREAD

**Issue by a15355447898a** [kenkangxgwe/lsp-wl#45]
所有的中文应该都会报错,但是我的代码关于中文的报错只有1000个
![QQ图片20210501222851](https://user-images.githubusercontent.com/62456287/116785637-435b3300-aacd-11eb-8fef-0a632a9c37aa.png)

**Comment by kenkangxgwe** [comment]
lol
1. 我最近会 push 一个不再提醒注释中非 ASCII 字符错误的版本。
2. 我试着去建一个差不多的文件测试一下为啥报错只有1000个。

**Comment by a15355447898a** [comment]
关于1:
代码中存在非ASCII字符(无论是在代码还是在注释),在WolframEngine运行会都提示Syntax::sntue: Unexpected end of file (probably unfinished expression) ,所以我觉得这个应该提醒

**Comment by kenkangxgwe** [comment]
2. 参见 https://github.com/Microsoft/vscode/issues/52736#issuecomment-400229573， 一个文件最多只会报 1000 个错误。

**Comment by kenkangxgwe** [comment]
1. 对于中文字符仍保持报错，但是可以在 VSCode 报错选项卡中过滤掉，或者在设置中的加入要抑制的报错类型，参见https://github.com/kenkangxgwe/lsp-wl#diagnostics
