### ISSUE TITLE
Unable To Connect to Wolfram Kernel

### ISSUE THREAD

**Issue by kands-code** [kenkangxgwe/lsp-wl#46]
我Mathematica升级到12.3后我就无法使用lsp的补全功能了，看起来是没有连接到wolfram内核上去

设置都是没问题的，内核我也都确认了没有问题

**Comment by kands-code** [comment]
重新拉取最新仓库后就正常了，抱歉打扰了( >﹏<。)

**Comment by kenkangxgwe** [comment]
感谢反馈！如果方便，可以告诉我你拉取的是 master 还是 develop 分支？https://github.com/kenkangxgwe/vscode-lsp-wl/issues/11 遇到了同样的问题，但是我手头暂时没有12.3。

**Comment by kands-code** [comment]
> 感谢反馈！如果方便，可以告诉我你拉取的是 master 还是 develop 分支？[kenkangxgwe/vscode-lsp-wl#11](https://github.com/kenkangxgwe/vscode-lsp-wl/issues/11) 遇到了同样的问题，但是我手头暂时没有12.3。

我一直拉取的是develop分支，我不清楚其他人的情况和我究竟是不是一样的(・∀・)

**Comment by kands-code** [comment]
![图片](https://user-images.githubusercontent.com/59006329/119229352-2ce34d00-bb4a-11eb-8f18-a3766de650cd.png)

如图所见，我尝试创建并编辑一个worlfram language script（wls）文件，但是我第一次编译的时候没有任何来自lsp的提示

![图片](https://user-images.githubusercontent.com/59006329/119229402-80ee3180-bb4a-11eb-808c-ec7204914433.png)

直到我重复打开关闭文件数次后才有正确的提示，

![图片](https://user-images.githubusercontent.com/59006329/119229426-a1b68700-bb4a-11eb-8f06-89d17e1da600.png)

但是我关闭文本编辑器（这里是neovim）后，后台的wolframkernel并没有关闭或中止，而是继续在后台运行，占据内存和使用cpu

![图片](https://user-images.githubusercontent.com/59006329/119229543-1a1d4800-bb4b-11eb-980d-65b8eb924828.png)

我感觉这是一个bug，前几次编辑时，lsp没能够连接/启动内核，所以没有对应提示，但在启动内核后，就有相应提示了，在完成文件编辑后，理应中止或关闭的内核仍在运行

**Comment by kenkangxgwe** [comment]
我试了一下 Wolfram Engine 12.3，连接不上内核，应该是 12.3 的 Bug，我已经提交给 Wolfram 了，暂时等一下他们的回复的同时，我想想有没有 workaround。

**Comment by kenkangxgwe** [comment]
你可以看一下这个方法能否帮助你吗？https://github.com/kenkangxgwe/lsp-wl/wiki#working-with-mathematica-123

**Comment by kands-code** [comment]
> 你可以看一下这个方法能否帮助你吗？https://github.com/kenkangxgwe/lsp-wl/wiki#working-with-mathematica-123

十分感谢您的帮忙，但是这个方法没能解决问题，在Disable掉`ZeroMQLink`后，我按照方法还安装了`1.1.22`版本

在做完一切后，我重启电脑，验证是否生效，结果打开Mathematica花了比以往更长的时间，并且在使用方面，我在使用nvim编辑时仍需要多次开启关闭文件以等待lsp连接上kernel，并且在编辑完成后内核仍然在运行中

![图片](https://user-images.githubusercontent.com/59006329/119601761-6bb02600-be1c-11eb-9ec1-532d86c8e3b0.png)

![图片](https://user-images.githubusercontent.com/59006329/119601834-900c0280-be1c-11eb-89b6-9ad8cb736836.png)

**Comment by kands-code** [comment]
我好像发现问题了，但是不知道要怎么做
![图片](https://user-images.githubusercontent.com/59006329/121473899-e6b93500-c9f5-11eb-9208-2158f075c441.png)

这是`:CocInfo`得到的信息，上面说lsp连接失败什么的，我不是很懂，还请大佬帮忙看看，感谢

**Comment by kands-code** [comment]
补充，应该不是我防火墙设置问题，我没有在防火墙的日志里发现什么相关信息

**Comment by kenkangxgwe** [comment]
你可以让我看一下你的 CocConfig 吗？

**Comment by kands-code** [comment]
> 你可以让我看一下你的 CocConfig 吗？

```json
{
    "coc.preferences.extensionUpdateCheck": "daily",
    "suggest.noselect": true,
    "suggest.enablePreselect": false,
    "coc.preferences.formatOnSaveFiletypes": [
        "json",
        "xml",
        "html",
        "css",
        "js",
        "latex",
        "python"
    ],
    "lsp-wl.enable": true,
    "lsp-wl.wolframExecutablePath": "/opt/Mathematica/Executables/wolfram",
    "lsp-wl.wolframLanguageServerPath": "/home/kands/.local/bin/lsp-wl",
    "lsp-wl.trace.server": "messages",
    "go.checkForUpdates": "disabled",
    "xml.java.home": "/usr/lib/jvm/default/",
    "texlab.path": "/usr/bin/texlab",
    "texlab.build.executable": "/usr/bin/xelatex",
    "texlab.build.onSave": true,
    "go.goplsPath": "/usr/bin/gopls",
    "rust-analyzer.enable": true,
    "rust-analyzer.server.path": "/usr/bin/rust-analyzer",
    "python.linting.pylintEnabled": true,
    "xml.server.workDir": "/home/kands/Documents/learnDocs/xml",
    "yaml.format.enable": true,
    "java.home": "/usr/lib/jvm/default",
    "java.configuration.maven.userSettings": "/home/kands/.local/bin/self-bin/maven-3.8/conf/settings.xml",
    "java.import.maven.enabled": true,
    "java.autobuild.enabled": false
}
```

这就是我的`coc-settings.json`的内容，希望能够有所帮助
