### ISSUE TITLE
The usage of lsp-wl integration with Emacs.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#48]
On Ubuntu 20.04, I try to use `lsp-wl` in the self compiled git master version of Emacs using the following settings in `~/.emacs.d/init.el` according to the notes [here](https://github.com/kenkangxgwe/lsp-wl/wiki#gnu-emacs):

```
(add-to-list 'lsp-language-id-configuration '(wolfram-mode . "Mathematica"))

(lsp-register-client
 (make-lsp-client :language-id 'wolfram
                  :new-connection (lsp-tcp-server-command
                                   (lambda (port)
                                     `("wolfram" ;; or "wolframscript"
                                       "-script" ;; or "-file"
                                       "~/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls"
                                       ,(concat
                                         "--socket="
                                         (number-to-string port)
                                         ))))
                  :major-modes '(wolfram-mode)
                  :server-id 'lsp-wl
                  ))
```
After Emacs has been started, I still don't know how to trigger/activate the corresponding functions supplied by `lsp-wl`, just as seen in `vscode` shown in the following screenshot:

![image](https://user-images.githubusercontent.com/11155854/119455380-203e3f00-bd6c-11eb-83b1-fa15c99b922d.png)

Any hints will be highly appreciated.

Regards,
HY

**Comment by kenkangxgwe** [comment]
Hi, have you run `(require 'lsp-mode)` or equivalent expr?

**Comment by hongyi-zhao** [comment]
Thanks for your comments, I installed the [lsp-mode](https://github.com/emacs-lsp/lsp-mode/) from [melpa](https://melpa.org/#/lsp-mode) and use the following settings in `~/.emacs.d/init.el`:

```
(add-to-list 'lsp-language-id-configuration '(wolfram-mode . "Mathematica"))

(lsp-register-client
 (make-lsp-client :language-id 'wolfram
                  :new-connection (lsp-tcp-server-command
                                   (lambda (port)
                                     `("wolfram" ;; or "wolframscript"
                                       "-script" ;; or "-file"
                                       "~/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls"
                                       ,(concat
                                         "--socket="
                                         (number-to-string port)
                                         ))))
                  :major-modes '(wolfram-mode)
                  :server-id 'lsp-wl
                  ))

(require 'lsp-mode)
```
But I still encounter the same problem.

Regards,
HY

**Comment by kenkangxgwe** [comment]
You should require it first

**Comment by hongyi-zhao** [comment]
Thank you. I change the config of `~/.emacs.d/init.el` into the following:

```
(require 'lsp-mode)
(add-to-list 'lsp-language-id-configuration '(wolfram-mode . "Mathematica"))

(lsp-register-client
 (make-lsp-client :language-id 'wolfram
                  :new-connection (lsp-tcp-server-command
                                   (lambda (port)
                                     `("wolfram" ;; or "wolframscript"
                                       "-script" ;; or "-file"
                                       "~/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls"
                                       ,(concat
                                         "--socket="
                                         (number-to-string port)
                                         ))))
                  :major-modes '(wolfram-mode)
                  :server-id 'lsp-wl
                  ))
```
See the following screenshot this time:

![image](https://user-images.githubusercontent.com/11155854/119459470-49f96500-bd70-11eb-8576-1a772468ef5f.png)

But I still don't know how to trigger the various features provided by this plugin, just as I have seen in `vscode`.

Regards,
HY

**Comment by kenkangxgwe** [comment]
Yeah, it will be a little tough if you haven't used emacs with `lsp-mode` before. Config is supposed to be activated with `wolfram-mode` enabled, so you also need to install [`wolfram-mode`](https://github.com/kawabata/wolfram-mode) (though it is out of maintenance for years) and require it in the config and then enable `lsp-mode` in the buffer you opened by calling `(lsp)`.

The features in VSCode are not exactly coming out of the box for emacs, because for every feature, you have to install a corresponding package or tweak the config (see https://emacs-lsp.github.io/lsp-mode/page/main-features/).

I am not sure what's your proficiency with emacs, but at least you can get the exact result from your VSCode screenshot after you have the `company-mode` installed. For evaluation buttons, it should be trigger from [`dap-mode`](https://emacs-lsp.github.io/dap-mode/) which is a sister mode of `lsp-mode`, but I forgot what config should you add to register dap-wl, I can look into it someday when I resolve some other issues in this repo.

There might be a long way to go if you want to stick to emacs (but it is worthy), so you might want to go through the lsp-mode docs first and welcome to leave comments here so I can help you with potential problems.

**Comment by hongyi-zhao** [comment]
Thank you. Let me discuss and deal with it in a divide-and-conquer manner.

The following is the file and directory hierarchy of Mathematica on my machine:
```
$ ls /opt/Wolfram/Mathematica/12.1/Executables/
math         Mathematica  mcc      WolframKernel
mathematica  MathKernel   wolfram  wolframscript
```
Based on the notes [here](https://github.com/kawabata/wolfram-mode/blob/be680190cac6ccf579dbce107deaae495928d1b3/wolfram-mode.el#L36), I figured out the following settings for my `~/.emacs.d/init.el':

```
  (autoload 'wolfram-mode "wolfram-mode" nil t)
  (autoload 'run-wolfram "wolfram-mode" nil t)
  (setq wolfram-program "/opt/Wolfram/Mathematica/12.1/Executables/MathKernel")
  (add-to-list 'auto-mode-alist '("\\.m$" . wolfram-mode))
  (setq wolfram-path "/opt/Wolfram/Mathematica/12.1/Executables") 
```
Am I right?

Regards,
HY

**Comment by kenkangxgwe** [comment]
For `wolfram-mode`, I just run `(require 'wolfram-mode)` after it is installed from Melpa and enable it in the buffer by `(wolfram-mode)`. I haven't set other variables in your config, so I cannot tell if they are correct.

**Comment by hongyi-zhao** [comment]
That said, presumably you've implemented the corresponding settings in the `lsp-wl`.

**Comment by kenkangxgwe** [comment]
So the basic steps of setting up lsp-wl on emacs should be:

1. Install `lsp-mode` and `wolfram-mode` and require them in emacs config.
2. Add the config in the wiki.
3. Open a wolfram code file and make sure `wolfram-mode` is activated.
4. Activate `lsp-mode` by `(lsp)`.
5. Enable lspfeatures by following the steps on its doc pages.

**Comment by hongyi-zhao** [comment]
It's well known that Emacs its powerful and tricky. I am far away from an expert, but I still believe it is worth the effort and persistence, as you have said. Below is my tries, settings and problems till now based on your above comments and my own understanding, as well as corresponding official documentations for relevant packages of Emacs.

I use the following elisp code snippet in `~/.emacs.d/init.el` to automatically install emacs packages  by specifying a list of package-name, in my case, the following packages `lsp-mode company company-box dap-mode wolfram-mode` will be installed automatically.

```
;https://github.com/bbatsov/prelude/blob/aaedc8537c04e4af7a53690b8bbb8522d5a35b9d/core/prelude-packages.el#L56
(defvar prelude-packages
  '(
    lsp-mode company company-box dap-mode wolfram-mode
   )
  "A list of packages to ensure are installed at launch.")

(defun prelude-packages-installed-p ()
  "Check if all packages in `prelude-packages' are installed."
  (cl-every #'package-installed-p prelude-packages))

(defun prelude-require-package (package)
  "Install PACKAGE unless already installed."
  (unless (memq package prelude-packages)
    (add-to-list 'prelude-packages package))
  (unless (package-installed-p package)
    (package-install package)))

(defun prelude-require-packages (packages)
  "Ensure PACKAGES are installed.
Missing packages are installed automatically."
  (mapc #'prelude-require-package packages))

(defun prelude-install-packages ()
  "Install all packages listed in `prelude-packages'."
  (unless (prelude-packages-installed-p)
    ;; check for new packages (package versions)
    (message "%s" "Emacs Prelude is now refreshing its package database...")
    (package-refresh-contents)
    (message "%s" " done.")
    ;; install the missing packages
    (prelude-require-packages prelude-packages)))

;; run package installation
(prelude-install-packages)
```
Then comes the corresponding configuration as follows:

```
(require 'wolfram-mode)
(require 'lsp-mode)
(add-to-list 'lsp-language-id-configuration '(wolfram-mode . "Mathematica"))

(lsp-register-client
 (make-lsp-client :language-id 'wolfram
                  :new-connection (lsp-tcp-server-command
                                   (lambda (port)
                                     `("wolfram" ;; or "wolframscript"
                                       "-script" ;; or "-file"
                                       "~/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls"
                                       ,(concat
                                         "--socket="
                                         (number-to-string port)
                                         ))))
                  :major-modes '(wolfram-mode)
                  :server-id 'lsp-wl
                  ))

;; With use-package:
(use-package company-box
  :hook (company-mode . company-box-mode))

;https://emacs-lsp.github.io/lsp-mode/page/main-features/
(setq company-minimum-prefix-length 1
      company-idle-delay 0.0) ;; default is 0.2
```
When I start Emacs with the above settings and open a Wolfram Mathematica package `.m` file, the screenshot is shown in the following:

![image](https://user-images.githubusercontent.com/11155854/119606822-cc902c00-be25-11eb-8cf9-25e6abb1adfc.png)

As you can see, the `wolfram-mode` won't be enabled automatically, till I issue the 'M-x wolfram-mode RET' command, then the screenshot will look like below:

![image](https://user-images.githubusercontent.com/11155854/119606996-25f85b00-be26-11eb-93fb-0a6671bc8c24.png)

Then I try to activate `lsp-mode` by `M-x lsp RET`, so far, the screenshot is as follows:

![image](https://user-images.githubusercontent.com/11155854/119607275-9606e100-be26-11eb-92d8-9ae067093da0.png)

But till now, I still can't see any clues to use the capabilities supplied by `lsp-wl` through Emacs. Ant hints will be highly appreciated.

Regards,
HY

**Comment by kenkangxgwe** [comment]
For lsp-mode, you need to be in a project directory. You can create a file in a folder like `~/project/test.wl` and then from the last screenshot, you can select the project folder with <kbd>I</kbd>. You can always look into the lsp log buffers to see the status or errors if any. I forget the buffer name but you may check from its doc.

**Comment by hongyi-zhao** [comment]
How to enter the following display effect which you have presented above:

![image](https://user-images.githubusercontent.com/11155854/119635055-e5103e80-be45-11eb-989d-0bb58571ace3.png)


Based on your comments, I tried with the following:
```
werner@X10DAi:~/project$ ls 
'#11.wl#'   test.wl
```

Then I run the following in Emacs:
```
Ctrl+x i /path/to/test.wl RET
M+x wolfram-mode RET
M-x lsp RET
```
Then I see the following in `Messages` buffer:
```
../Public/repo/github.com/jwiegley/use-package.git/bind-key.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
../Public/repo/code.orgmode.org/bzg/org-mode.git/lisp/org-table.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' [2 times]
../Public/repo/code.orgmode.org/bzg/org-mode.git/lisp/org-list.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
../Public/repo/code.orgmode.org/bzg/org-mode.git/lisp/org-src.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
../Public/repo/code.orgmode.org/bzg/org-mode.git/lisp/org.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'
For information about GNU Emacs and the GNU system, type C-h C-a.
LSP :: test.wl not in project or it is blacklisted.
```

**Comment by kenkangxgwe** [comment]
> LSP :: test.wl not in project or it is blacklisted.

As it says, the test.wl is not in project. You need to import the project by selecting a folder when you open the file. Further info is available in [projectile docs](https://docs.projectile.mx/projectile/index.html).

--------

Use `<kbd>I</kbd>` to input a key stroke.

**Comment by hongyi-zhao** [comment]
> and then from the last screenshot, you can select the project folder with <kbd>I</kbd>. 

I still can't figure out the exact command sequence of Emacs you meant above. 

But, based on your above comments about [projectile](https://docs.projectile.mx/projectile/index.html) and the official guide [here](https://github.com/bbatsov/projectile#installation), I installed the `projectile` package and add the following configuration into my `~/.emacs.d/init.el`:
```
(projectile-mode +1)
;; Recommended keymap prefix on macOS
;(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
;; Recommended keymap prefix on Windows/Linux
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)  
```
Then I open the directory `~/project` from Emacs, and then I click on the file located under this directory from within Emacs. Finally run the following commands:
```
M-x wolfram-mode RET
M-x lsp RET
```
Now, I see the following messages in lsp log buffers named as `*lsp-log*` as shown below:

![image](https://user-images.githubusercontent.com/11155854/119693676-178a5d80-be7f-11eb-85b1-bc6d359654a4.png)

And the following file editing window:

![image](https://user-images.githubusercontent.com/11155854/119693944-5b7d6280-be7f-11eb-97e2-3205342c6364.png)

But I still can't see any clues to use/activate/trigger the capabilities supplied by `lsp-wl` through Emacs till now.  

Regards,
HY

**Comment by kenkangxgwe** [comment]
[This](https://asciinema.org/a/yh7Pb5ymIdA7dAEWUW9yj2eIt) records an MWE on my side. Please take a look if it helps.

**Comment by hongyi-zhao** [comment]
Your record is based on [spacemacs](https://github.com/syl20bnr/spacemacs), and I'm using vanilla Emacs. This may bring some additional difficulty to my scenario. 
 
Why do you run on a source file of this repo as following to do the testing? 

`$ env term=xterm-256color emacs ~/projects/lsp-wl-develop/init.wls`

I have tried it with the exact same config and command order as yours but still can't access the corresponding capabilities supplied by this plugin. 

My next step is to study the following related documents and demonstrations:

https://github.com/emacs-lsp/lsp-mode#presentationsdemos
https://www.youtube.com/playlist?list=PLEoMzSkcN8oNvsrtk_iZSb94krGRofFjN

And try to ask on the official Emacs lists, if necessary.

Regards,
HY

**Comment by kenkangxgwe** [comment]
Just tried with vanilla emacs on my side. It can connect to the server with no problem. Can you take a look at the `*lsp-log*` buffer if the server is connected successfully?

**Comment by hongyi-zhao** [comment]
```
$ emacs /home/werner/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls

M-x wolfram-mode RET
M-x lsp RET
```
At this point, the `*lsp-log*` buffer on my side is shown below:

![image](https://user-images.githubusercontent.com/11155854/119832485-cd61b480-bf30-11eb-957e-96afe65aad94.png)


As a further check, the Mathematica Kernel relevant processes can't be found at all:

```
werner@X10DAi:~$ ps -aux| grep Mathematica |grep -v grep
werner@X10DAi:~$
```
But for the vscode case, the following processes will be listed after the debugging connection has been established successfully:
```
werner@X10DAi:~$ ps -aux| grep Mathematica |grep -v grep
werner   2929546  178  0.0 4717756 252264 ?      Rl   21:23   0:26 /opt/Wolfram/Mathematica/12.1/SystemFiles/Kernel/Binaries/Linux-x86-64/WolframKernel -script /home/werner/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls --socket=6536 --clientProcessId=2928512
werner   2932810  8.3  0.0 1039668 151096 ?      SNl  21:23   0:00 /opt/Wolfram/Mathematica/12.1/SystemFiles/Kernel/Binaries/Linux-x86-64/WolframKernel -subkernel -noinit -nopaclet -wstp -linkprotocol SharedMemory -linkconnect -linkname p7z6v_shm
```

**Comment by kenkangxgwe** [comment]
It seems that the `wolfram` executable might not be started correctly. Could you change the `wolfram` path in your config as a detailed path or try `WolframKernel`?

**Comment by hongyi-zhao** [comment]
I tried with each of the following settings in `~/.emacs.d/init.el`:
```
     "wolfram"
     "wolframscript"       
     "/opt/Wolfram/Mathematica/12.1/Executables/wolfram"
     "/opt/Wolfram/Mathematica/12.1/Executables/wolframscript"                       
     "/opt/Wolfram/Mathematica/12.1/Executables/WolframKernel" 
```

But after I run the following commands:

```
$  emacs /home/werner/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls
M-x wolfram-mode RET
M-x lsp RET
```
I always notice the information in the `*Messages*` buffer similar to the following:

![image](https://user-images.githubusercontent.com/11155854/119954228-5b8d7780-bfd1-11eb-8770-7532a65752a3.png)

And on my side, I can confirm the following variables are set in the `PATH`:
```
werner@X10DAi:~$ which wolfram
/usr/local/bin/wolfram
werner@X10DAi:~$ which wolframscript 
/usr/bin/wolframscript
```

**Comment by hongyi-zhao** [comment]
Could you please share with me the complete configuration of the vanilla Emacs used by you to do the test discussed here?

**Comment by hongyi-zhao** [comment]
I finally switched to [Wolfram Workbench](https://www.wolfram.com/workbench/) considering the following reasons:

1. Wolfram Workbench is the official product of Wolfram.
2. Emacs' community doesn't support wolfram language due to its proprietary/close source feature.
3. Eclipse is an IDE, while vscode is just an IDE-like editor.
4. The currently implemented [function set](https://reference.wolfram.com/workbench/index.jsp) in Wolfram Workbench is rich and powerful enough, so any third party implementation developed from scratch, just like the job done by this project, will require tremendous effort and time to be able to match it.

**Comment by hongyi-zhao** [comment]
Despite my comments above, I still deeply admire your efforts in developing this project.
