### ISSUE TITLE
The strange results given by the second complement behaviour of lsp-wl in vscode.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#49]
On Ubuntu 20.04, I use lsp-wl with the latest stable version of vscode. I find a strange completion behaviour as described below:

Firstly, we type `\` and some character, say, `f`, as shown below:

![image](https://user-images.githubusercontent.com/11155854/119475882-1f170d00-bd80-11eb-8a84-d16835159e25.png)

Then, we click on `Backspace` to delete the `f`, and re-type `f`. This time, the pop-up window of the completion entries will look like below:

![image](https://user-images.githubusercontent.com/11155854/119476922-1a9f2400-bd81-11eb-80da-08f74028e88f.png)

As you can see, they are different. Any hints for this problem?

Regards,
HY

**Comment by kenkangxgwe** [comment]
The current implementation only triggers aliases if you type `\` once, so hitting backspace will interrupt further completion. I can make an enhancement around this. Thanks for the feedback!

**Comment by kenkangxgwe** [comment]
Fixed in 660b816884ad7d74a668ecf876ddfc5df9ae38a9
