### ISSUE TITLE
The different display style for \[Pi] in vscode and MMA.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#52]
On Ubuntu 20.04, I test the math symbols display in `vscode` and MMA respectively with the following example file:

```
$ cat 11.wl 
\[Pi]*2
```
In the debug console of `vscode` with the help of `lsp-wl`:

![image](https://user-images.githubusercontent.com/11155854/119948514-7eb52880-bfcb-11eb-8765-41e94d62709f.png)

In MMA:

![image](https://user-images.githubusercontent.com/11155854/119948725-b4f2a800-bfcb-11eb-9146-e3cac5c2cfd3.png)

Why it can't be displayed as the corresponding math symbol in `vscode`?

**Comment by kenkangxgwe** [comment]
Remember that in the VSCode config, what you invoke is a wolfram kernel (either `wolfram` or `wolframscript`, not MMA or its FrontEnd). If you type in `\[Pi]` in the kernel, the result is expected to be `Pi`.

**Comment by hongyi-zhao** [comment]
> not MMA or its FrontEnd

Is it possible for us to call MMA, via its terminal version, `math`, from within `vscode`? I noticed that the math symbols can be displayed correctly with the [`StandardForm`](https://reference.wolfram.com/language/ref/StandardForm.html) directive in Mathematica's terminal version, i.e., `math`, as shown below:

![image](https://user-images.githubusercontent.com/11155854/119952431-955d7e80-bfcf-11eb-90eb-c631c7a8fa81.png)

**Comment by kenkangxgwe** [comment]
> call MMA, via its terminal version, `math`

This is merely the kernel, not the FrontEnd.

Notice that when you call `StandardForm`, the underlying string is not what it displays. Thus, the "standard form" version of `\[Pi]` is indeed `"\!\(\*RowBox[{\"\[Pi]\"}]\)"`. You can test this by `\[Pi] // StandardForm // ToString // FullForm`. Thus, unless you can do something from `\[Pi]` to a "full form" `"π"`, you cannot display it samely in the raw text as the FrontEnd does.
