### ISSUE TITLE
Generate a plot in debug console.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#54]
Is it possible to let `lsp-wl` generate a plot in debug console, say, for the following command?

`Plot[Sin[x]/x, {x, -20, 20}, PlotRange -> All]`

Regards,
HY

**Comment by kenkangxgwe** [comment]
It does what the kernel does. The kernel is able to popup a window for the graphics by `` <<JavaGraphics`  ``.

**Comment by hongyi-zhao** [comment]
I see. Thank you. It works:

![image](https://user-images.githubusercontent.com/11155854/119966011-75cd5280-bfdd-11eb-98fd-aed2063212ef.png)

The only downside to this approach is that it doesn't allow us to manipulate the plot the way we can do in the `Notebook`.

Another problem I noticed that it the ` << JavaGraphics` ` can't be automatically completed with any hints.
