### ISSUE TITLE
Feature request: completion based on substring starting at arbitrary position and case-insensitive match.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#55]
Currently, the completion is only based on the exact beginning string match. Considering that there are so many functions/keywords available in `MMA`, I think the completion based on substring starting at arbitrary position and case-insensitive match is a worthwhile feature.

The possible drawback of my above suggestions may be a performance penalty to some extent, i.e., the response speed may be slower than the current implementation.

Regards,
HY

**Comment by kenkangxgwe** [comment]
The fuzzy & case-insensitive matching is already supported. However, the first character must be matched, which I think is not too bad comparing to matches starting from an arbitrary position.
![image](https://user-images.githubusercontent.com/8650023/120097323-b1067900-c0e4-11eb-86c1-1030df93163a.png)
