### ISSUE TITLE
The error result of the delayed replacement rule displayed on debug console.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#58]
The testing code:
```
i = 0;
{a, b, c, d, c, a, c, b} /. c :> (i++; Echo[i, "replacement "]; f)
```
vscode:

![image](https://user-images.githubusercontent.com/11155854/120056721-b033ff80-c070-11eb-9cce-a97306bf07be.png)

MMA:

![image](https://user-images.githubusercontent.com/11155854/120056727-bf1ab200-c070-11eb-93f5-61050157be51.png)

**Comment by kenkangxgwe** [comment]
This works fine for me. Did you ever assign your `a` with `{1,2,3,4,5,6,7,8}` in a previous evaluation?

![image](https://user-images.githubusercontent.com/8650023/120068546-059eeb00-c036-11eb-8c9e-ddd65a1d3045.png)

**Comment by hongyi-zhao** [comment]
You're right. See the testing code shown below:
```
a={1,2,3,4,5,6,7,8};

i=0;
{a, b, c, d, c, a, c, b} /. c :> (i++; Echo[i, "replacement "]; f)
(* Clear["Global`*"]; *)
Clear["a"];
{a, b, c, d, c, a, c, b} /. c :> (i++; Echo[i, "replacement "]; f)
```
![image](https://user-images.githubusercontent.com/11155854/120126867-388cde80-c1f0-11eb-8b3a-5a8045e20cdb.png)
