### ISSUE TITLE
Is syntax highlight provided?

### ISSUE THREAD

**Issue by singularitti** [kenkangxgwe/lsp-wl#6]
I follow the steps in the installation section but found there was no syntax highlighting? Currently, I am using [this plugin](https://marketplace.visualstudio.com/items?itemName=shigma.vscode-wl) for syntax highlighting.

**Comment by kenkangxgwe** [comment]
No, the syntax highlight is not included in the Language Server, but this plugin will provide the semantic highlight in the future.

**Comment by singularitti** [comment]
Ah, I just found this is claimed in the plugin page:

> This is an early release, so more features are on the way. Syntax highlight is NOT supported according to the design of LSP, but there are already some good enough extensions like Wolfram Language.

Personally, I wish this link could be replaced by [what I mentioned](https://marketplace.visualstudio.com/items?itemName=shigma.vscode-wl), because the plugin's syntax highlighting is better than [Wolfram Language](https://marketplace.visualstudio.com/items?itemName=flipphillips.wolfram-language).

**Comment by kenkangxgwe** [comment]
@singularitti , I have tried @shigma's plugin and found their syntax highlighting is sometimes too fancy to me.
Create a PR, if you like, to mention both of the plugins.

**Comment by singularitti** [comment]
Sure.
