### ISSUE TITLE
Unable to close the Wolfram kernel in time

### ISSUE THREAD

**Issue by kands-code** [kenkangxgwe/lsp-wl#61]
在将`ZeroMQLink`换成`1.1.22`版本后，lsp能够连接上wolfram kernel了，但是在每次编辑完后，启动的wolfram人会在后台占用内存和消耗cpu，有时候甚至能占用2G内存 (仅在后台运行，无其他操作，暂无截图)
- Mathematica Version: `12.3.0 for Linux x86 (64-bit) (May 10, 2021)`
- Editor: Neovim + coc.nvim
- branch: develop

编辑前无Wolfram Kernel进程，退出编辑后就出现了进程，而且不会自己关闭
![图片](https://user-images.githubusercontent.com/59006329/123186419-aa440980-d4ca-11eb-9915-8f024b6ee4e4.png)

而且系统占用还有那么高
![图片](https://user-images.githubusercontent.com/59006329/123186485-d3fd3080-d4ca-11eb-9bb8-b142ea3bbfad.png)

**Comment by kenkangxgwe** [comment]
你可以试一下最新的 develop branch吗？理论上最晚关闭 vim 10s 之后就会关闭

**Comment by kands-code** [comment]
> 你可以试一下最新的 develop branch吗？理论上最晚关闭 vim 10s 之后就会关闭

![图片](https://user-images.githubusercontent.com/59006329/124488473-78904400-dde2-11eb-9c06-1428c8b20d6a.png)

我尝试一下，结果lsp直接不工作了，不知道是什么原因

**Comment by kenkangxgwe** [comment]
我看最后的留言是不工作，但是你关闭了这个议题，请问是否已解决？
