### ISSUE TITLE
Cannot get extension working on VSCode

### ISSUE THREAD

**Issue by 89sundown** [kenkangxgwe/lsp-wl#62]
Just getting this output in VSCode and I cannot get the extension working after following the documentation. Is there any additional configuration that needs to happen on Mathematica? Do I need to open a port in a notebook within Mathematica? 

```
[Error - 11:03:51 PM] Connection to server is erroring. Shutting down server.
[Trace - 11:03:51 PM] Sending request 'shutdown - (1)'.
[Error - 11:03:51 PM] Connection to server is erroring. Shutting down server.
[Error - 11:03:51 PM] Connection to server is erroring. Shutting down server.
[Error - 11:03:51 PM] Connection to server is erroring. Shutting down server.
[Error - 11:03:51 PM] Connection to server is erroring. Shutting down server.
[INFO  2021-06-26T23:03:51] Server listening from port 6536...
```

I've followed the troubleshooting tip as well. 

`PacletInstall["ZeroMQLink" -> "1.1.22", ForceVersionInstall -> True]`

**Comment by kenkangxgwe** [comment]
Hi Max, I want to get more information from your issue. Could you try:
1. Checkout the latest `develop` branch if you were at `master` branch.
2. Follow the instruction in https://github.com/kenkangxgwe/lsp-wl/wiki#enable-logging to enable the log. Reproduce your problem and copy the log file after the server shuts down for 5 times.

**Comment by 89sundown** [comment]
![picture](https://user-images.githubusercontent.com/46584802/123543766-21bda700-d71e-11eb-9ba4-eb1942fa292e.JPG)

I've checked out the develop branch, and you can see the log file in the attached.

**Comment by kenkangxgwe** [comment]
1. May I see your VSCode settings?
2. Could you run `FindFile["ZeroMQLink`"]` in your wolfram executable?

**Comment by 89sundown** [comment]
I just realized the settings has two tabs inside VSCode. I only edited the user page. Mathematica also isn't finding that file. 


User:
![settings](https://user-images.githubusercontent.com/46584802/123621171-efbd4b00-d7d8-11eb-97aa-a85b63fb5169.JPG)

Workspace: 
![workspace](https://user-images.githubusercontent.com/46584802/123621255-04014800-d7d9-11eb-8aa7-ed6b7f78409f.JPG)

Mathematica:
![mathematica settings](https://user-images.githubusercontent.com/46584802/123621104-e0d69880-d7d8-11eb-8259-c456b310f38c.JPG)

**Comment by kenkangxgwe** [comment]
1. Editing the "User" tab is good enough.
2. Sorry, it should be `` FindFile["ZeroMQLink`"] ``. Could you try again?

**Comment by 89sundown** [comment]
I'm away from that computer now. I won't be able to get back to you for another 10 hours.

**Comment by 89sundown** [comment]
Here is the output. I'm a member of the unofficial Wolfram discord server. The below link is an invite. It might be easier to do this live if you're interested. 

[https://discord.gg/gj6VKAK](url)

![wolfram-troubleshoot](https://user-images.githubusercontent.com/46584802/123707898-76554500-d838-11eb-830d-35d15d0b5f73.JPG)

**Comment by kenkangxgwe** [comment]
It seems that the default ZeroMQLink is not set to 1.1.22. It's still using 1.2.1 as shown above. I am already in that discord server. I will ping you there.

**Comment by PhyX-Meow** [comment]
Now latest Mathematica is 12.3.1, which ```FindFile["ZeroMQLink`"]``` gives me this:
![image](https://user-images.githubusercontent.com/17513581/132126237-c7bf2692-fc72-484a-b71d-50d0dc5a61ca.png)
I look into the folder and found it's version 1.2.0. Still I can't get language server working. Any working around?

**Comment by kenkangxgwe** [comment]
Hi @PhyX-Meow , As discussed above and in the [wiki](https://github.com/kenkangxgwe/lsp-wl/wiki#working-with-mathematica-123), you need ZeroMQLink 1.1.* to make the language server work.

**Comment by PhyX-Meow** [comment]
But the problem I cannot load it, even I delete the version in user folder, mma would use the built-in one.

**Comment by kenkangxgwe** [comment]
Can you try the latest revision on the `develop` branch? I think it will automatically handle it for you.

**Comment by kenkangxgwe** [comment]
Wolfram solved this upstream bug recently. Please manually upgrade the ZeroMQLink paclet

```mathematica
PacletInstall["ZeroMQLink"]
```
ref: https://github.com/kenkangxgwe/lsp-wl/wiki#working-with-mathematica-123130
