### ISSUE TITLE
LSP can't connect to VSCode (macOS), Mathematica 12.3.1

### ISSUE THREAD

**Issue by p-pavel** [kenkangxgwe/lsp-wl#65]
This is the development branch. 

On startup I got the following in Output tab of VSCode:

(I believe I once seen a discussion about ZeroMQLink but can't find it)

<pre>
PacletInstall::newervers: A paclet named ZeroMQLink with a newer version number (1.2.4) is already installed. If you wish to install an older version, use PacletUninstall to remove the existing version first, or call PacletInstall with ForceVersionInstall->True.

Get::noopen: Cannot open ZeroMQLink`.
[INFO  2021-10-06T13:27:19] Initializing Wolfram Language Server
[INFO  2021-10-06T13:27:24] Language server is connecting the client through
socket.
[INFO  2021-10-06T13:27:24] Server listening from port 6667...

DataType`TypeCheck::mispat: 
   WolframLanguageServer`Server`Private`SocketConnect[6667, TCP]
     doesn't match the pattern of "client" in 
    WolframLanguageServer`Server`Private`WorkState.
[ERROR 2021-10-06T13:27:24]
Which[WolframLanguageServer`Server`Private`SocketReadyQ[WolframLanguageServer`Se
rver`Private`SocketConnect[6667, TCP]],
WolframLanguageServer`Server`Private`handleMessageList[WolframLanguageServer`Ser
ver`Private`ReadMessages[WolframLanguageServer`Server`Private`SocketConnect[6667
, TCP]], WolframLanguageServer`Server`Private`WorkState[<|initialized -> False,
openedDocs -> <||>, debugSession ->
WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False, server
-> Null, client -> Null|>], scheduledTasks -> {}, caches ->
<|textDocument/signatureHelp -> <||>, textDocument/documentSymbol -> <||>,
textDocument/documentLink -> <||>, textDocument/documentColor -> <||>,
textDocument/codeLens -> <||>, textDocument/publishDiagnostics -> <||>|>,
pendingServerRequests -> <||>, config -> <|configFileConfig ->
WolframLanguageServer`Server`Private`loadConfig[]|>, client ->
WolframLanguageServer`Server`Private`SocketConnect[6667, TCP]|>]],
WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False, server
-> Null, client -> Null|>][server] =!= Null &&
WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False, server
-> Null, client -> Null|>][client] === Null &&
Length[WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False,
[INFO  2021-10-06T13:27:24] Closing socket connection...

DataType`TypeCheck::mispat: 
   WolframLanguageServer`Server`Private`SocketConnect[6667, TCP]
     doesn't match the pattern of "client" in 
    WolframLanguageServer`Server`Private`WorkState.
[ERROR 2021-10-06T13:27:24] Server stopped abnormally.
[ERROR 2021-10-06T13:27:24]
Which[WolframLanguageServer`Server`Private`SocketReadyQ[WolframLanguageServer`Se
rver`Private`SocketConnect[6667, TCP]],
WolframLanguageServer`Server`Private`handleMessageList[WolframLanguageServer`Ser
ver`Private`ReadMessages[WolframLanguageServer`Server`Private`SocketConnect[6667
, TCP]], WolframLanguageServer`Server`Private`WorkState[<|initialized -> False,
openedDocs -> <||>, debugSession ->
WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False, server
-> Null, client -> Null|>], scheduledTasks -> {}, caches ->
<|textDocument/signatureHelp -> <||>, textDocument/documentSymbol -> <||>,
textDocument/documentLink -> <||>, textDocument/documentColor -> <||>,
textDocument/codeLens -> <||>, textDocument/publishDiagnostics -> <||>|>,
pendingServerRequests -> <||>, config -> <|configFileConfig ->
WolframLanguageServer`Server`Private`loadConfig[]|>, client ->
WolframLanguageServer`Server`Private`SocketConnect[6667, TCP]|>]],
WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False, server
-> Null, client -> Null|>][server] =!= Null &&
WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False, server
-> Null, client -> Null|>][client] === Null &&
Length[WolframLanguageServer`Server`Private`DebugSession[<|initialized -> False,

</pre>

**Comment by kenkangxgwe** [comment]
Maybe dupe with https://github.com/kenkangxgwe/lsp-wl/issues/63?

Could you try out the latest `develop` branch to see if the problem is solved? Thanks!

**Comment by p-pavel** [comment]
I believe this is the latest commit cfb8157113345f4c1224a5eb179a7be854714751

**Comment by kenkangxgwe** [comment]
Could you show me the output if you run ``FindFile["ZeroMQLink`"]`` in MMA?

**Comment by p-pavel** [comment]
"/Users/ppavel/Library/Mathematica/Paclets/Repository/ZeroMQLink-1.2.\
4/Kernel/ZeroMQLink.m"

**Comment by kenkangxgwe** [comment]
I think you just need to disabel 1.2.4 and install 1.1.22
```
PacletDisable["ZeroMQLink" -> "1.2.4"]
PacletInstall["ZeroMQLink" -> "1.1.22", ForceVersionInstall -> True]
```

Run ``FindFile["ZeroMQLink`"]`` again, to ensure it is 1.1.22 by default. And then try again with the language server.

**Comment by p-pavel** [comment]
Thanks, that helped. Is something wrong with ZeroMQLink 1.2.4?

**Comment by kenkangxgwe** [comment]
Sadly, something is wrong after version 1.2.

**Comment by kenkangxgwe** [comment]
Wolfram solved this upstream bug recently. Please manually upgrade the ZeroMQLink paclet

```mathematica
PacletInstall["ZeroMQLink"]
```
ref: https://github.com/kenkangxgwe/lsp-wl/wiki#working-with-mathematica-123130
