### ISSUE TITLE
hover shows nothing

### ISSUE THREAD

**Issue by zhaoruiyang98** [kenkangxgwe/lsp-wl#68]
# Environment
* OS: Windows 10
* Mathematica version: 12.3.1
* Wolfram Language Server version: 0.1.9
* vscode version: 1.69.2
* I disabled all vscode plugins except Wolfram Language Server.

# Description
Hi kenkangxgwe,

Thanks for developing this wonderful tool.
After installation, it works well except the hover feature. I expect to see the documentation for functions and variables from the `System`` context, but it shows nothing.

I tried the master branch and the develop branch, neither works.

I changed the logging level to `debug` according to the wiki page and turned the plugin's trace level to `verbose`, but the debug info seems not very useful...
```
[Trace - 02:34:52] Sending request 'textDocument/hover - (160)'.
Params: {
    "textDocument": {
        "uri": "file://<path to file>",
    },
    "position": {
        "line": 4,
        "character": 1
    }
}

[Trace - 02:34:52] Received response 'textDocument/hover - (160)' in 12ms.
No result returned.
```
It correctly points out where my mouse is hovering and returns nothing.

# Maybe related
In the beginning, when I type a function like `Sin`, the completion does not show the usage.  And I find this solved issue #31, the situation described there is actually what I meet. After I manually setting `$Language = "SimpliedChinese"` in `init.m`, this problem is solved, although this should have been solved in [2109999](https://github.com/kenkangxgwe/lsp-wl/commit/210999920f5c4941263b87560813c08e9cfd2380).

**Comment by kenkangxgwe** [comment]
Hi @zhaoruiyang98 , I wonder what will `List::usage` give you if don't set `$Language = "SimplifiedChinese"` in `init.m`?

**Comment by zhaoruiyang98** [comment]
![image](https://user-images.githubusercontent.com/43402887/182785308-c921a5ac-b468-4c89-bb1e-fae41d86cbf0.png)
On master branch, it shows nothing, but works on develop branch. `List::usage` just returns `List::usage` (wolfram.exe). Maybe this issue is related to my Mathematica installation?

**Comment by kenkangxgwe** [comment]
1. Please use `develop` branch for now.
2. VSCode will relay on the configuration on wolfram, so your workaround is reasonable and may not require any change on LSP.

**Comment by zhaoruiyang98** [comment]
Okay, I'm using `develop` branch now.

I wonder is there any difference when LSP deals with hover compared to completion? Maybe there is workaround for hover as well.

**Comment by kenkangxgwe** [comment]
Is hovering still showing you nothing?

**Comment by zhaoruiyang98** [comment]
Yes

**Comment by kenkangxgwe** [comment]
Could you run
```mathematica
List::usage // Replace[{_MessageName :> ({"FrontEnd", UsingFrontEnd[CurrentValue[$FrontEnd, Language]]}),_:>{"Kernel",$Language}}]
```
in kernel?

**Comment by zhaoruiyang98** [comment]
It returns `{Kernel, ChineseSimplified}` if I set `$Language = "ChineseSimplified"` in `init.m`, otherwise it returns `{FrontEnd, ChineseSimplified}`

**Comment by kenkangxgwe** [comment]
Try
```mathematica
FindFile[FileNameJoin[{$InstallationDirectory, "SystemFiles", "Kernel", "TextResources", $Language, "Usage.m"}]]
```

**Comment by zhaoruiyang98** [comment]
I will always set `$Language = "ChineseSimplified"` in `init.m` in the following:

It returns `C:\Program Files\Wolfram Research\Mathematica\12.3\SystemFiles\Kernel\TextResources\ChineseSimplified\Usage.m`

**Comment by kenkangxgwe** [comment]
I think I found a bug on my side as well, I will provide a fix sometime tomorrow maybe.

**Comment by zhaoruiyang98** [comment]
Thank you for your time! Thanks a lot.

**Comment by kenkangxgwe** [comment]
Hi, I think the top of develop branch should fix the issue now. Let me know if it also works on your side.

**Comment by zhaoruiyang98** [comment]
It works now! Many thanks~
